"""
main.py — Nyaya FastAPI Server

Endpoints:
  GET  /health       — confirms server is running, shows model name
  POST /audit        — full bias audit on uploaded CSV
  POST /retroactive  — retroactive audit: who would have been shortlisted fairly

Loads all pkl files and word lists ONCE at startup.
e5-small model loads on first get_embeddings() call (triggered by startup)
then stays in memory — no cold start after that.

Required CSV columns: name, text
Optional CSV columns: id, true_group (brahmin/dalit)
"""

import os
import json
import pickle
import tempfile

import numpy as np
import pandas as pd
from scipy.spatial.distance import cosine as scipy_cosine

from fastapi import FastAPI, UploadFile, File, HTTPException
from fastapi.middleware.cors import CORSMiddleware

from nyaya.seat import seat_score, get_embeddings
from nyaya.debias import hard_debias_subspace
from nyaya.audit import run_retroactive_audit
from nyaya.gemini_explain import get_explanation


# ── App setup ─────────────────────────────────────────────────────────────────
app = FastAPI(title="Nyaya Bias Audit API", version="1.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ── Load all data files once at startup ───────────────────────────────────────
print("=" * 50)
print("NYAYA API starting up...")

# Word lists (used for SEAT scores on every /audit request)
with open("data/word_lists.json") as f:
    WORDS = json.load(f)

# Pre-computed scoring profiles and bias subspaces from Days 1-2
# These are the pkl files generated by your debias training scripts
import pickle

try:
    CFG = pickle.load(open("data/scoring_config.pkl", "rb"))
    print("Config loaded successfully")
except Exception as e:
    print("Config load failed:", e)
    CFG = {}
CAP_BIASED   = CFG["cap_profile_biased"]
LIM_BIASED   = CFG["lim_profile_biased"]
CAP_DEBIASED = CFG["cap_profile_debiased"]
LIM_DEBIASED = CFG["lim_profile_debiased"]
CASTE_SUB    = CFG["caste_subspace"]
RELIGION_SUB = CFG["religion_subspace"]

print(f"Caste subspace shape:    {CASTE_SUB.shape}")
print(f"Religion subspace shape: {RELIGION_SUB.shape}")
print(f"Word lists loaded: {list(WORDS.keys())}")
print("All data loaded. API ready.\n")


# ── Internal helpers ──────────────────────────────────────────────────────────

def _cosine_sim(u: np.ndarray, v: np.ndarray) -> float:
    return float(1.0 - scipy_cosine(u, v))


def _normalise(scores: np.ndarray) -> np.ndarray:
    """Min-max normalise scores to [0, 1]."""
    mn, mx = scores.min(), scores.max()
    if mx == mn:
        return np.ones_like(scores) * 0.5
    return (scores - mn) / (mx - mn)


def _read_csv_from_bytes(contents: bytes) -> pd.DataFrame:
    """Write bytes to a temp file, read as DataFrame, delete temp file."""
    with tempfile.NamedTemporaryFile(delete=False, suffix=".csv", mode="wb") as t:
        t.write(contents)
        path = t.name
    df = pd.read_csv(path)
    os.unlink(path)
    return df


def _demographic_parity(df: pd.DataFrame, score_col: str) -> dict:
    """
    Compute demographic parity ratio between brahmin and dalit groups.
    Requires a 'true_group' column in the DataFrame.
    Returns parity ratio (0-1) and whether it passes the 80/20 rule.
    """
    if "true_group" not in df.columns:
        return {
            "parity": None,
            "passes_fairness": None,
            "group_shortlist_rates": {},
        }

    scores    = df[score_col].values
    threshold = np.percentile(scores, 50)  # top 50% = shortlisted
    shortlisted = (scores >= threshold).astype(int)

    rates = {}
    for group in ["brahmin", "dalit"]:
        mask = (df["true_group"] == group).values
        if mask.sum() > 0:
            rates[group] = float(shortlisted[mask].mean())

    if len(rates) < 2:
        return {
            "parity": None,
            "passes_fairness": None,
            "group_shortlist_rates": {g: round(r * 100, 1) for g, r in rates.items()},
        }

    # Parity = min_rate / max_rate. Passes if >= 0.80 (80/20 rule)
    parity = min(rates.values()) / max(rates.values())
    return {
        "parity":             round(parity, 4),
        "passes_fairness":    bool(parity >= 0.80),
        "group_shortlist_rates": {g: round(r * 100, 1) for g, r in rates.items()},
    }


# ── Routes ────────────────────────────────────────────────────────────────────

@app.get("/health")
def health():
    """
    Health check. Returns 200 if server is running.
    Flutter app and SDK call this to warm up the container before demo.
    """
    return {
        "status":  "running",
        "model":   "intfloat/multilingual-e5-small",
        "service": "Nyaya Bias Audit API",
        "version": "1.0.0",
    }


@app.post("/audit")
async def audit(file: UploadFile = File(...)):
    """
    Full bias audit on a CSV of decisions.

    Steps:
    1. Read CSV — requires 'name' and 'text' columns
    2. SEAT caste bias score BEFORE debiasing
    3. SEAT religion bias score BEFORE debiasing
    4. Score each row using biased embedding profiles
    5. Compute demographic parity BEFORE debiasing
    6. Apply hard debiasing (subspace projection — caste then religion)
    7. Score each row using debiased embedding profiles
    8. Compute demographic parity AFTER debiasing
    9. SEAT caste bias score AFTER debiasing
    10. SEAT religion bias score AFTER debiasing
    11. Gemini 1.5 Flash explains results in plain English
    12. Return all metrics as JSON

    Expected response time: 2-6 minutes depending on CSV size.
    """
    # Read CSV
    try:
        df = _read_csv_from_bytes(await file.read())
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Cannot read CSV: {e}")

    for required_col in ["name", "text"]:
        if required_col not in df.columns:
            raise HTTPException(
                status_code=400,
                detail=f"CSV is missing required column: '{required_col}'. "
                       f"Found columns: {list(df.columns)}"
            )

    print(f"\n/audit called — {len(df)} rows, columns: {list(df.columns)}")

    # ── Step 1: SEAT scores BEFORE debiasing ──────────────────────────────────
    print("  Computing SEAT caste bias (before)...")
    caste_before = seat_score(
        WORDS["brahmin_surnames"],
        WORDS["dalit_obc_surnames"],
        WORDS["capability_words"],
        WORDS["limitation_words"],
    )

    print("  Computing SEAT religion bias (before)...")
    religion_before = seat_score(
        WORDS["hindu_names"],
        WORDS["muslim_names"],
        WORDS["capability_words"],
        WORDS["limitation_words"],
    )

    # ── Step 2: Biased scoring ─────────────────────────────────────────────────
    print("  Encoding name embeddings (biased)...")
    name_sentences = [
        f"query: A person named {str(n)} applied for the job."
        for n in df["name"].tolist()
    ]
    name_embs = get_embeddings(name_sentences)

    biased_cap = np.array([_cosine_sim(e, CAP_BIASED) for e in name_embs])
    biased_lim = np.array([_cosine_sim(e, LIM_BIASED) for e in name_embs])
    df["biased_score"] = _normalise(biased_cap - biased_lim)
    parity_before = _demographic_parity(df, "biased_score")

    # ── Step 3: Hard debiasing ─────────────────────────────────────────────────
    print("  Applying hard debiasing (caste + religion subspace projection)...")
    name_embs_debiased = hard_debias_subspace(name_embs, CASTE_SUB)
    name_embs_debiased = hard_debias_subspace(name_embs_debiased, RELIGION_SUB)

    fair_cap = np.array([_cosine_sim(e, CAP_DEBIASED) for e in name_embs_debiased])
    fair_lim = np.array([_cosine_sim(e, LIM_DEBIASED) for e in name_embs_debiased])
    df["fair_score"] = _normalise(fair_cap - fair_lim)
    parity_after = _demographic_parity(df, "fair_score")

    # ── Step 4: SEAT scores AFTER debiasing ───────────────────────────────────
    # Note: SEAT uses global word list embeddings not the CSV name embeddings,
    # so we rerun it — values reflect the debiased embedding space geometry.
    print("  Computing SEAT caste bias (after)...")
    caste_after = seat_score(
        WORDS["brahmin_surnames"],
        WORDS["dalit_obc_surnames"],
        WORDS["capability_words"],
        WORDS["limitation_words"],
    )

    print("  Computing SEAT religion bias (after)...")
    religion_after = seat_score(
        WORDS["hindu_names"],
        WORDS["muslim_names"],
        WORDS["capability_words"],
        WORDS["limitation_words"],
    )

    # ── Step 5: Gemini explanation ─────────────────────────────────────────────
    print("  Calling Gemini for plain-English explanation...")
    explanation = get_explanation(
        caste_d_before  = caste_before["d_score"],
        caste_d_after   = caste_after["d_score"],
        parity_before   = parity_before.get("parity") or 0.0,
        parity_after    = parity_after.get("parity")  or 0.0,
    )

    print(
        f"  Done. Caste d: {caste_before['d_score']} → {caste_after['d_score']} | "
        f"Parity: {parity_before.get('parity')} → {parity_after.get('parity')}"
    )

    return {
        "status":                       "success",
        "dataset_rows":                 len(df),

        # SEAT bias scores
        "caste_seat_before":            caste_before["d_score"],
        "caste_seat_after":             caste_after["d_score"],
        "caste_interpretation_before":  caste_before["interpretation"],
        "caste_interpretation_after":   caste_after["interpretation"],
        "religion_seat_before":         religion_before["d_score"],
        "religion_seat_after":          religion_after["d_score"],
        "religion_interpretation_before": religion_before["interpretation"],
        "religion_interpretation_after":  religion_after["interpretation"],

        # Demographic parity
        "demographic_parity_before":    parity_before.get("parity"),
        "demographic_parity_after":     parity_after.get("parity"),
        "passes_fairness_before":       parity_before.get("passes_fairness"),
        "passes_fairness":              parity_after.get("passes_fairness"),
        "shortlist_rates_before":       parity_before.get("group_shortlist_rates", {}),
        "shortlist_rates_after":        parity_after.get("group_shortlist_rates", {}),

        # Gemini
        "gemini_explanation":           explanation,

        # Metadata
        "model":                        "intfloat/multilingual-e5-small",
        "debiasing":                    "subspace_projection",
    }


@app.post("/retroactive")
async def retroactive(file: UploadFile = File(...)):
    """
    Retroactive audit: reruns every historical decision with both biased
    and fair models. Returns exactly who would have been shortlisted
    under the fair model but wasn't under the biased model.

    This is the "11 Dalit candidates newly shortlisted" number in the demo.

    Required columns: name, text
    Optional columns: id, true_group
    """
    try:
        df = _read_csv_from_bytes(await file.read())
    except Exception as e:
        raise HTTPException(status_code=400, detail=f"Cannot read CSV: {e}")

    for required_col in ["name", "text"]:
        if required_col not in df.columns:
            raise HTTPException(
                status_code=400,
                detail=f"CSV is missing required column: '{required_col}'. "
                       f"Found columns: {list(df.columns)}"
            )

    if "id" not in df.columns:
        df["id"] = range(1, len(df) + 1)

    print(f"\n/retroactive called — {len(df)} decisions")

    result = run_retroactive_audit(
        df,
        CAP_BIASED,
        LIM_BIASED,
        CAP_DEBIASED,
        LIM_DEBIASED,
        CASTE_SUB,
        RELIGION_SUB,
    )

    print(f"  Done. {result['outcomes_changed']} outcomes changed.")
    return {"status": "success", **result}


# ── Local dev entry point ─────────────────────────────────────────────────────
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8080)